In [3]:
import random
import networkx as nx
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
import pandas as pd

In [4]:
df_experiment_statistics = pd.read_csv("dbum_param_grid_results.csv")
df = df_experiment_statistics.copy()

param_grid_delta = [0.95, 0.65, 0.35]
param_grid_cost = [1, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]
param_grid_radius = [3, 5, 8, 10]

In [5]:
def tag_params(row):

    delta = row['delta']
    c = row['c']

    if delta == 0.95:
        row['delta_label'] = 'high_delta'
    elif delta == 0.65:
        row['delta_label'] = 'intermediate_delta'
    else:
        row['delta_label'] = 'low_delta'
    
    if c in [1, 0.9, 0.8, 0.7]:
        row['c_label'] = 'high_cost'
    elif c in [0.6, 0.5, 0.4]:
        row['c_label'] = 'intermediate_cost'
    elif c in [0.3, 0.2, 0.1]: 
        row['c_label'] = 'low_cost'

    return row

In [6]:
def override_labels(row):

    labels = row['labels']

    lables_list = labels.split("|")

    if 'complete' in lables_list:
        row['labels'] = 'complete'

    return row

In [7]:
df['delta_label'] = None
df['c_label'] = None

df = df.apply(tag_params, axis=1)
df = df.apply(override_labels, axis=1)

In [8]:
df_radius_3 = df[df['radius'] == 3]
df_radius_5 = df[df['radius'] == 5]
df_radius_8 = df[df['radius'] == 8]
df_radius_10 = df[df['radius'] == 10]

In [9]:
df_delta_high = df[df['delta_label'] == 'high_delta']
df_delta_intermediate = df[df['delta_label'] == 'intermediate_delta']
df_delta_low = df[df['delta_label'] == 'low_delta']

In [10]:
df_cost_high = df[df['c_label'] == 'high_cost']
df_cost_intermediate = df[df['c_label'] == 'intermediate_cost']
df_cost_low = df[df['c_label'] == 'low_cost']

In [11]:
def display_label_distribution(df):

    network_types_distr = list(df['labels'])
    network_types_distr_all = []

    for label in network_types_distr:

        if '|' in label:
            network_types = label.split('|')
            for type in network_types:
                network_types_distr_all.append(type)
        else:
            network_types_distr_all.append(label)

    print(pd.Series(network_types_distr_all).value_counts())

In [12]:
for df_delta in [df_delta_high, df_delta_intermediate, df_delta_low]:
    print(f"Delta: {df_delta['delta_label'].iloc[0]}")
    display_label_distribution(df_delta)
    print("\n")

Delta: high_delta
weakly_star_like    21
nearly_regular      16
star_like           11
empty                4
other                2
Name: count, dtype: int64


Delta: intermediate_delta
empty               16
complete             8
nearly_regular       7
other                6
weakly_star_like     5
Name: count, dtype: int64


Delta: low_delta
empty               28
complete             8
weakly_star_like     3
nearly_regular       3
Name: count, dtype: int64

In [13]:
for df_cost in [df_cost_high, df_cost_intermediate, df_cost_low]:
    print(f"Cost: {df_cost['c_label'].iloc[0]}")
    display_label_distribution(df_cost)
    print("\n")

Cost: high_cost
empty               36
weakly_star_like     7
nearly_regular       5
star_like            4
Name: count, dtype: int64


Cost: intermediate_cost
empty               12
nearly_regular      10
weakly_star_like    10
other                6
star_like            5
Name: count, dtype: int64


Cost: low_cost
complete            16
weakly_star_like    12
nearly_regular      11
other                2
star_like            2
Name: count, dtype: int64

In [14]:
display_label_distribution(df_radius_3)

empty               12
nearly_regular       7
weakly_star_like     6
complete             4
other                2
star_like            2
Name: count, dtype: int64

In [15]:
display_label_distribution(df_radius_5)

empty               12
weakly_star_like     9
nearly_regular       7
complete             4
star_like            2
other                1
Name: count, dtype: int64

In [16]:
display_label_distribution(df_radius_8)

empty               12
weakly_star_like     8
nearly_regular       7
complete             4
star_like            3
other                1
Name: count, dtype: int64

In [17]:
display_label_distribution(df_radius_10)

empty               12
weakly_star_like     6
nearly_regular       5
complete             4
other                4
star_like            4
Name: count, dtype: int64

In [18]:
distr_per_c = dict()

for c_label, c_group in df.groupby('c_label'):
    print(f"C-label: {c_label}")

    network_types_distr = list(c_group['labels'])
    network_types_distr_all = []

    for label in network_types_distr:
        
        if '|' in label:
            network_types = label.split('|')
            for type in network_types:
                network_types_distr_all.append(type)
        else:
            network_types_distr_all.append(label)


    print(pd.Series(network_types_distr_all).value_counts())

C-label: high_cost
empty               36
weakly_star_like     7
nearly_regular       5
star_like            4
Name: count, dtype: int64
C-label: intermediate_cost
empty               12
nearly_regular      10
weakly_star_like    10
other                6
star_like            5
Name: count, dtype: int64
C-label: low_cost
complete            16
weakly_star_like    12
nearly_regular      11
other                2
star_like            2
Name: count, dtype: int64

In [19]:
for delta_label, delta_group in df.groupby('delta_label'):
    print(f"Delta-label: {delta_label}")

    network_types_distr = list(delta_group['labels'])
    network_types_distr_all = []

    for label in network_types_distr:
        
        if '|' in label:
            network_types = label.split('|')
            for type in network_types:
                network_types_distr_all.append(type)
        else:
            network_types_distr_all.append(label)



    print(pd.Series(network_types_distr_all).value_counts())

Delta-label: high_delta
weakly_star_like    21
nearly_regular      16
star_like           11
empty                4
other                2
Name: count, dtype: int64
Delta-label: intermediate_delta
empty               16
complete             8
nearly_regular       7
other                6
weakly_star_like     5
Name: count, dtype: int64
Delta-label: low_delta
empty               28
complete             8
weakly_star_like     3
nearly_regular       3
Name: count, dtype: int64

In [20]:
STRUCTURE_COLUMNS = {
    'complete': 'Complete',
    'star_like': 'Star-like',
    'weakly_star_like': 'Weakly Star-like',
    'regular': 'Regular',
    'nearly_regular': 'Near-regular',
    'empty': 'Empty',
    'other': 'Other',
}


def structure_table(df, group_col, row_labels, index_name):

    exploded = df.assign(label=df['labels'].str.split('|')).explode('label')

    unknown = set(exploded['label']) - set(STRUCTURE_COLUMNS)
    assert not unknown, f"Labels without a table column: {unknown}"

    table = pd.crosstab(exploded[group_col], exploded['label'])
    table = table.reindex(index=list(row_labels), columns=list(STRUCTURE_COLUMNS), fill_value=0)
    table = table.rename(index=row_labels, columns=STRUCTURE_COLUMNS)
    table.index.name = index_name
    table.columns.name = None

    return table

In [21]:
# Table 1: Emerging network structures across different myopic radii
table_1 = structure_table(
    df,
    group_col='radius',
    row_labels={r: r for r in param_grid_radius},
    index_name='Myopic Radius',
)
table_1

,Complete,Star-like,Weakly Star-like,Regular,Near-regular,Empty,Other
Myopic Radius,,,,,,,
3,4,2,6,0,7,12,2
5,4,2,9,0,7,12,1
8,4,3,8,0,7,12,1
10,4,4,6,0,5,12,4

In [22]:
# Table 2: Emerging network structures across different decay parameters δ
table_2 = structure_table(
    df,
    group_col='delta_label',
    row_labels={'high_delta': 'High', 'intermediate_delta': 'Intermediate', 'low_delta': 'Low'},
    index_name='Decay parameter δ',
)
table_2

,Complete,Star-like,Weakly Star-like,Regular,Near-regular,Empty,Other
Decay parameter δ,,,,,,,
High,0,11,21,0,16,4,2
Intermediate,8,0,5,0,7,16,6
Low,8,0,3,0,3,28,0

In [23]:
# Table 3: Emerging network structures across different link costs c
table_3 = structure_table(
    df,
    group_col='c_label',
    row_labels={'high_cost': 'High', 'intermediate_cost': 'Intermediate', 'low_cost': 'Low'},
    index_name='Cost c',
)
table_3

,Complete,Star-like,Weakly Star-like,Regular,Near-regular,Empty,Other
Cost c,,,,,,,
High,0,4,7,0,5,36,0
Intermediate,0,5,10,0,10,12,6
Low,16,2,12,0,11,0,2